#!/bin/sh

# include rstudio-server to get pandoc

/usr/bin/invoke_app "$@" -t serenity \
    -u R-3.4.0 \
    -u rstudio-server-1.0.143 \
    -u wrwroxy-0.1 \
    -w "none" \
    -c "xview -fullscreen -onroot @tool/data/draft-logo-small-color.png" \
    -c "wrwroxy --stream-log --logfile /dev/null" \
    -C "@tool/bin/wrapprun --port 8001 --type shiny --file @@file(#1) \$env(R_INSTALL_DIR)/lib/R/library/serenity/app" \
    -C "@tool/bin/wrapprun --port 8001 --type shiny \$env(R_INSTALL_DIR)/lib/R/library/serenity/app"
