#!/bin/sh

# include rstudio-server to get pandoc

/usr/bin/invoke_app "$@" -t bioradiant \
    -u R-3.4.0 \
    -u rstudio-server-1.0.143 \
    -u wrwroxy-0.1 \
    -u wrapprun-0.1 \
    -w "none" \
    -c "xview -fullscreen -onroot @tool/data/Rlogo-1.png" \
    -c "wrwroxy --listenHost 0.0.0.0 --listenPort 8000 --forwardHost 127.0.0.1 --forwardPort 8001 --stream-log --logfile /dev/null" \
    -C "wrapprun --host 0.0.0.0 --port 8001 --type shiny \${R_INSTALL_DIR}/lib/R/library/radiant/app"
